# Generated by Django 5.1.8 on 2026-07-15 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nazwa")),
                ("slug", models.SlugField(unique=True)),
                (
                    "config_key",
                    models.SlugField(unique=True, verbose_name="klucz konfiguracji"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktywna"),
                ),
            ],
            options={
                "verbose_name": "strona",
                "verbose_name_plural": "strony",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EditSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=180, verbose_name="temat rozmowy"),
                ),
                (
                    "target_url",
                    models.URLField(
                        max_length=1000, verbose_name="adres edytowanej strony"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Przygotowywanie"),
                            ("active", "Aktywna"),
                            ("published", "Opublikowana"),
                            ("failed", "Błąd"),
                            ("archived", "Zarchiwizowana"),
                        ],
                        default="preparing",
                        max_length=20,
                    ),
                ),
                ("workspace_path", models.TextField(blank=True)),
                ("baseline_commit", models.CharField(blank=True, max_length=64)),
                ("baseline_manifest", models.JSONField(blank=True, default=dict)),
                ("last_response_id", models.CharField(blank=True, max_length=200)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edit_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edit_sessions",
                        to="editor.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Użytkownik"),
                            ("assistant", "Asystent"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("response_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="editor.editsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_hash", models.CharField(max_length=64)),
                ("summary", models.CharField(max_length=240)),
                ("changed_files", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="editor.editsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SiteMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("editor", "Edytor"),
                            ("publisher", "Edytor i publikujący"),
                        ],
                        default="editor",
                        max_length=20,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="editor.site",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="site",
            name="users",
            field=models.ManyToManyField(
                related_name="editable_sites",
                through="editor.SiteMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="sitemembership",
            constraint=models.UniqueConstraint(
                fields=("site", "user"), name="unique_site_user"
            ),
        ),
    ]
