# Generated by Django 5.1.8 on 2026-07-15 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models
from urllib.parse import urlsplit, urlunsplit


def move_existing_messages_to_page_chats(apps, schema_editor):
    EditSession = apps.get_model("editor", "EditSession")
    PageConversation = apps.get_model("editor", "PageConversation")
    ChatMessage = apps.get_model("editor", "ChatMessage")
    for edit_session in EditSession.objects.all().iterator():
        parts = urlsplit(edit_session.target_url)
        normalized = urlunsplit((parts.scheme.lower(), parts.netloc.lower(), parts.path or "/", parts.query, ""))
        label = f"{parts.path or '/'}{'?' + parts.query if parts.query else ''}"[:180]
        conversation = PageConversation.objects.create(
            session_id=edit_session.pk,
            target_url=normalized,
            normalized_url=normalized,
            label=label,
            last_response_id=edit_session.last_response_id,
        )
        ChatMessage.objects.filter(session_id=edit_session.pk).update(conversation_id=conversation.pk)


def detach_existing_messages(apps, schema_editor):
    ChatMessage = apps.get_model("editor", "ChatMessage")
    ChatMessage.objects.update(conversation=None)


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="PageConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_url",
                    models.URLField(max_length=1000, verbose_name="adres podstrony"),
                ),
                ("normalized_url", models.CharField(max_length=1000)),
                ("label", models.CharField(blank=True, max_length=180)),
                ("last_response_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="editor.editsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="editor.pageconversation",
            ),
        ),
        migrations.RunPython(move_existing_messages_to_page_chats, detach_existing_messages),
        migrations.AddConstraint(
            model_name="pageconversation",
            constraint=models.UniqueConstraint(
                fields=("session", "normalized_url"), name="unique_session_page_url"
            ),
        ),
    ]
