# Generated by Django 5.1.8 on 2026-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_chatmessage_context_pageconversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="editsession",
            name="preview_transforms",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
