# Generated by Django 5.2.16 on 2026-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_editsession_preview_transforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="config_key",
            field=models.SlugField(
                help_text="Nazwa pliku TOML bez rozszerzenia. Przykładowo wartość „jerozolima” oznacza plik site_configs/jerozolima.toml.",
                unique=True,
                verbose_name="plik konfiguracji strony",
            ),
        ),
    ]
