# Generated by Django 5.2.16 on 2026-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0004_alter_site_config_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="editsession",
            name="copy_bytes_done",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="editsession",
            name="copy_bytes_total",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="editsession",
            name="copy_files_done",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="editsession",
            name="copy_files_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="editsession",
            name="copy_stage",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
